### ISSUE TITLE
Doubts about positioning files

### ISSUE THREAD

**Issue by czoia** [shinobisoft/vendor_lge_proprietary#1]
Dear @shinobisoft I'm a newbie of cyanogenMod compile world, I've the problem you resolve in xda forum about lg optimus L90 vendor files but I not understand where I need to copy these files. Can you help me?
Regards,
czoia

**Comment by shinobisoft** [comment]
I've since lost my entire build environment but if memory serves me correctly, those files go to your CM11 source directory in the vendor sub-directory. For example, my CM11 folder was in my home folder, /home/shinobisoft/CM11, so the vendor files were in /home/shinobisoft/CM11/vendor. I could be wrong however. I'm no longer developing for any devices, and L90 D-415 was the first one that I ever developed for.
I'm sorry I couldn't be of more help.
